version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: foodle:latest
    container_name: foodle
    volumes:
      - .:/foodle
    ports:
      - 8080:8080